// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const AUTH_STORAGE_KEY = 'shadow-clone-survivor-auth';

function cleanEnvValue(value: string | undefined) {
  return value?.trim().replace(/^["']|["']$/g, '');
}

function migrateAuthStorage(supabaseUrl: string) {
  if (typeof window === 'undefined') return;
  try {
    const projectRef = new URL(supabaseUrl).hostname.split('.')[0];
    const defaultStorageKey = `sb-${projectRef}-auth-token`;
    if (!localStorage.getItem(AUTH_STORAGE_KEY)) {
      const existingSession = localStorage.getItem(defaultStorageKey);
      if (existingSession) localStorage.setItem(AUTH_STORAGE_KEY, existingSession);
    }
  } catch {
    // Best effort only; Supabase can still create a fresh persisted session.
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = cleanEnvValue(import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL);
  const SUPABASE_PUBLISHABLE_KEY = cleanEnvValue(
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_ANON_KEY
  );

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  migrateAuthStorage(SUPABASE_URL);

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      storageKey: AUTH_STORAGE_KEY,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

